export const TEAM_LOGOS: Record<string, string> = {
    // --- Série A ---
    'Flamengo': 'https://upload.wikimedia.org/wikipedia/commons/2/2e/Flamengo_braz_logo.svg',
    'Palmeiras': 'https://upload.wikimedia.org/wikipedia/commons/1/10/Palmeiras_logo.svg',
    'São Paulo': 'https://upload.wikimedia.org/wikipedia/commons/6/6f/Brasao_do_Sao_Paulo_Futebol_Clube.svg',
    'Sao Paulo': 'https://upload.wikimedia.org/wikipedia/commons/6/6f/Brasao_do_Sao_Paulo_Futebol_Clube.svg',
    'Corinthians': 'https://upload.wikimedia.org/wikipedia/pt/b/b4/Corinthians_simbolo.png',
    'Atlético Mineiro': 'https://upload.wikimedia.org/wikipedia/commons/5/5f/Atlético_Mineiro_logo.svg',
    'Atletico Mineiro': 'https://upload.wikimedia.org/wikipedia/commons/5/5f/Atlético_Mineiro_logo.svg',
    'Fluminense': 'https://upload.wikimedia.org/wikipedia/commons/a/ad/Fluminense_FC_escudo.png',
    'Grêmio': 'https://upload.wikimedia.org/wikipedia/commons/thumb/d/d0/Gremio_logo.svg/1200px-Gremio_logo.svg.png',
    'Gremio': 'https://upload.wikimedia.org/wikipedia/commons/thumb/d/d0/Gremio_logo.svg/1200px-Gremio_logo.svg.png',
    'Internacional': 'https://upload.wikimedia.org/wikipedia/commons/f/f1/Escudo_do_Sport_Club_Internacional.svg',
    'Botafogo': 'https://upload.wikimedia.org/wikipedia/commons/c/cb/Escudo_Botafogo.svg',
    'Vasco da Gama': 'https://upload.wikimedia.org/wikipedia/commons/e/e8/VascodaGama.svg',
    'Vasco': 'https://upload.wikimedia.org/wikipedia/commons/e/e8/VascodaGama.svg',
    'Cruzeiro': 'https://upload.wikimedia.org/wikipedia/commons/b/b8/Cruzeiro_Esporte_Clube_%28logo%29.svg',
    'Bahia': 'https://upload.wikimedia.org/wikipedia/pt/2/20/Esporte_Clube_Bahia_logo.png',
    'Fortaleza': 'https://upload.wikimedia.org/wikipedia/commons/4/42/Fortaleza_Esporte_Clube_logo.svg',
    'Athletico Paranaense': 'https://upload.wikimedia.org/wikipedia/commons/c/c7/Club_Athletico_Paranaense_2019.svg',
    'Athletico-PR': 'https://upload.wikimedia.org/wikipedia/commons/c/c7/Club_Athletico_Paranaense_2019.svg',
    'Cuiabá': 'https://upload.wikimedia.org/wikipedia/commons/2/26/Cuiaba_Esporte_Clube_logo.svg',
    'Cuiaba': 'https://upload.wikimedia.org/wikipedia/commons/2/26/Cuiaba_Esporte_Clube_logo.svg',
    'Red Bull Bragantino': 'https://upload.wikimedia.org/wikipedia/pt/9/94/Red_Bull_Bragantino.png',
    'Bragantino': 'https://upload.wikimedia.org/wikipedia/pt/9/94/Red_Bull_Bragantino.png',
    'Atlético Goianiense': 'https://upload.wikimedia.org/wikipedia/commons/a/a2/Atlético_Goianiense_logo.svg',
    'Atletico GO': 'https://upload.wikimedia.org/wikipedia/commons/a/a2/Atlético_Goianiense_logo.svg',
    'Juventude': 'https://upload.wikimedia.org/wikipedia/commons/5/52/Juventude_Esporte_Clube_logo.svg',
    'Criciúma': 'https://upload.wikimedia.org/wikipedia/commons/6/62/Criciuma_Esporte_Clube_logo.svg',
    'Criciuma': 'https://upload.wikimedia.org/wikipedia/commons/6/62/Criciuma_Esporte_Clube_logo.svg',
    'Vitória': 'https://upload.wikimedia.org/wikipedia/pt/6/62/Esporte_Clube_Vitória_logo.png',
    'Vitoria': 'https://upload.wikimedia.org/wikipedia/pt/6/62/Esporte_Clube_Vitória_logo.png',

    // --- Série B ---
    'Santos': 'https://upload.wikimedia.org/wikipedia/commons/1/15/Santos_Logo.png',
    'Sport Recife': 'https://upload.wikimedia.org/wikipedia/pt/1/18/Sport_Club_do_Recife.png',
    'Sport': 'https://upload.wikimedia.org/wikipedia/pt/1/18/Sport_Club_do_Recife.png',
    'Ceará': 'https://upload.wikimedia.org/wikipedia/commons/6/61/Ceara_Sporting_Club_logo.svg',
    'Ceara': 'https://upload.wikimedia.org/wikipedia/commons/6/61/Ceara_Sporting_Club_logo.svg',
    'Goiás': 'https://upload.wikimedia.org/wikipedia/commons/0/05/Goias_Esporte_Clube_logo.svg',
    'Goias': 'https://upload.wikimedia.org/wikipedia/commons/0/05/Goias_Esporte_Clube_logo.svg',
    'Vila Nova': 'https://upload.wikimedia.org/wikipedia/commons/3/36/Vila_Nova_Futebol_Clube_logo.svg',
    'América Mineiro': 'https://upload.wikimedia.org/wikipedia/commons/a/ac/América_Mineiro_logo.svg',
    'America-MG': 'https://upload.wikimedia.org/wikipedia/commons/a/ac/América_Mineiro_logo.svg',
    'Chapecoense': 'https://upload.wikimedia.org/wikipedia/commons/c/c5/Associação_Chapecoense_de_Futebol_logo.svg',
    'Avaí': 'https://upload.wikimedia.org/wikipedia/commons/8/87/Avai_Futebol_Clube.svg',
    'Avai': 'https://upload.wikimedia.org/wikipedia/commons/8/87/Avai_Futebol_Clube.svg',
    'Ponte Preta': 'https://upload.wikimedia.org/wikipedia/commons/2/2e/Associação_Atlética_Ponte_Preta_logo.svg',
    'Guarani': 'https://upload.wikimedia.org/wikipedia/commons/3/3d/Guarani_Futebol_Clube.svg',
    'CRB': 'https://upload.wikimedia.org/wikipedia/commons/f/f3/Clube_de_Regatas_Brasil.svg',
    'Novorizontino': 'https://upload.wikimedia.org/wikipedia/commons/8/83/Grêmio_Novorizontino_logo.svg',
    'Mirassol': 'https://upload.wikimedia.org/wikipedia/commons/8/85/Mirassol_Futebol_Clube_logo.svg',
    'Ituano': 'https://upload.wikimedia.org/wikipedia/pt/7/77/Ituano_Futebol_Clube_logo.png',
    'Botafogo-SP': 'https://upload.wikimedia.org/wikipedia/pt/e/e9/Botafogo_Futebol_Clube_%28Ribeirão_Preto%29.png',
    'Paysandu': 'https://upload.wikimedia.org/wikipedia/commons/7/77/Paysandu_Sport_Club_logo.svg',
    'Remo': 'https://upload.wikimedia.org/wikipedia/commons/5/52/Clube_do_Remo_logo.svg',
    'Coritiba': 'https://upload.wikimedia.org/wikipedia/commons/8/82/Coritiba_Foot_Ball_Club_2008.svg',
    'Operário-PR': 'https://upload.wikimedia.org/wikipedia/commons/8/82/Operário_Ferroviário_Esporte_Clube.png',
    'Operario-PR': 'https://upload.wikimedia.org/wikipedia/commons/8/82/Operário_Ferroviário_Esporte_Clube.png',
    'Operario Ferroviario': 'https://upload.wikimedia.org/wikipedia/commons/8/82/Operário_Ferroviário_Esporte_Clube.png',
    'Brusque': 'https://upload.wikimedia.org/wikipedia/commons/f/f3/Brusque_Futebol_Clube.png',
    'Amazonas': 'https://upload.wikimedia.org/wikipedia/commons/6/6e/Amazonas_Futebol_Clube.png',

    // --- Paranaense ---
    'Londrina': 'https://upload.wikimedia.org/wikipedia/pt/c/c5/Londrina_Esporte_Clube_logo.png',
    'Cianorte': 'https://upload.wikimedia.org/wikipedia/commons/8/8a/Cianorte_Futebol_Clube.png',
    'Azuriz': 'https://upload.wikimedia.org/wikipedia/pt/e/ed/Azuriz_Futebol_Clube.png',
    'São Joseense': 'https://upload.wikimedia.org/wikipedia/commons/5/59/Independiente_Futebol_São_Joseense_logo.png',
    'Sao Joseense': 'https://upload.wikimedia.org/wikipedia/commons/5/59/Independiente_Futebol_São_Joseense_logo.png',
    'Maringá': 'https://upload.wikimedia.org/wikipedia/commons/e/ea/Maringá_Futebol_Clube.png',
    'Maringa': 'https://upload.wikimedia.org/wikipedia/commons/e/ea/Maringá_Futebol_Clube.png',
    'Cascavel': 'https://upload.wikimedia.org/wikipedia/commons/e/e4/Futebol_Clube_Cascavel_logo.svg',
    'FC Cascavel': 'https://upload.wikimedia.org/wikipedia/commons/e/e4/Futebol_Clube_Cascavel_logo.svg',
    'Galo Maringá': 'https://upload.wikimedia.org/wikipedia/commons/7/72/Galo_Maringá.png',
    'Andraus': 'https://upload.wikimedia.org/wikipedia/commons/b/b3/Clube_Andraus_Brasil.png',
    'PSTC': 'https://upload.wikimedia.org/wikipedia/commons/3/3f/PSTC_logo.png',

    // --- Paraibano & Others (User reported these) ---
    'Sousa': 'https://upload.wikimedia.org/wikipedia/commons/5/57/Sousa_Esporte_Clube.png',
    'Botafogo-PB': 'https://upload.wikimedia.org/wikipedia/commons/e/e4/Botafogo_Futebol_Clube_%28João_Pessoa%29.svg',
    'Treze': 'https://upload.wikimedia.org/wikipedia/commons/7/73/Treze_Futebol_Clube.svg',
    'Campinense': 'https://upload.wikimedia.org/wikipedia/commons/7/7d/Campinense_Clube.svg',
    'Sampaio Corrêa': 'https://upload.wikimedia.org/wikipedia/pt/e/e7/Sampaio_Correa_Futebol_Clube_logo.png',
    'Sampaio Correa': 'https://upload.wikimedia.org/wikipedia/pt/e/e7/Sampaio_Correa_Futebol_Clube_logo.png',
    'Maranhão': 'https://upload.wikimedia.org/wikipedia/commons/c/c8/Maranhão_Atlético_Clube.png',
    'Maranhao': 'https://upload.wikimedia.org/wikipedia/commons/c/c8/Maranhão_Atlético_Clube.png',
    'Moto Club': 'https://upload.wikimedia.org/wikipedia/commons/5/52/Moto_Club_de_São_Luís.svg',
    'Imperatriz': 'https://upload.wikimedia.org/wikipedia/commons/6/63/Sociedade_Imperatriz_de_Desportos.png',

    // --- Europe Top ---
    'Man City': 'https://upload.wikimedia.org/wikipedia/pt/0/02/Manchester_City_Football_Club.png',
    'Arsenal': 'https://upload.wikimedia.org/wikipedia/pt/5/53/Arsenal_FC.svg',
    'Liverpool': 'https://upload.wikimedia.org/wikipedia/pt/0/0c/Liverpool_FC.svg',
    'Man United': 'https://upload.wikimedia.org/wikipedia/pt/b/b6/Manchester_United_FC_crest.svg',
    'Real Madrid': 'https://upload.wikimedia.org/wikipedia/pt/9/98/Real_Madrid.png',
    'Barcelona': 'https://upload.wikimedia.org/wikipedia/pt/4/43/FC_Barcelona_crest.svg',
    'PSG': 'https://upload.wikimedia.org/wikipedia/commons/a/a7/Paris_Saint-Germain_F.C..svg',
    'Bayern Munich': 'https://upload.wikimedia.org/wikipedia/commons/1/1b/FC_Bayern_München_logo_%282017%29.svg',
    'Juventus': 'https://upload.wikimedia.org/wikipedia/commons/a/a8/Juventus_FC_2017_logo.svg'
}
